version: '3.8'
services:
  fastapi:
    container_name: fastapi
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - chromadb
    networks:
      default_bridge:
        ipv4_address: 172.22.0.2

networks:
  default_bridge:
    ipam:
      config:
        - subnet: 172.22.0.0/16